"""Regions Geometry configuration."""

# dissolve geometries as NAME_0 (country) level
LEVEL0_REGIONS = [
    "Dominican Republic",
    "Bahamas",
    "Anguilla",
    "Saint Vincent and the Grenadines",
    "Curaçao",
    "Suriname",
    "French Guiana",
    "Mauritius",
    "Reunion",
    "Guadeloupe",
    "Bonaire, Sint Eustatius and Saba",
    "Saint-Barthélemy",
    "Saint-Martin",
    "Sint Maarten",
    "Virgin Islands, U.S.",
    "British Virgin Islands",
    "Qatar",
    "Jamaica",
    "Haiti",
    "Puerto Rico",
    "Saint Kitts and Nevis",
    "Antigua and Barbuda",
    "Montserrat",
    "Dominica",
    "Martinique",
    "Saint Lucia",
    "Barbados",
    "Grenada",
    "Trinidad and Tobago",
    "El Salvador",
    "Lesotho",
    "Swaziland",
    "Malawi",
    "Liberia",
    "Guinea-Bissau",
    "Equatorial Guinea",
    "Burundi",
    "Rwanda",
    "Sri Lanka",
    "United Arab Emirates",
    "Bahrain",
    "Kuwait",
    "Cyprus",
    "Northern Cyprus",
    "Lebanon",
    "Kosovo",
    "Montenegro",
    "Macedonia",
    "Slovenia",
    "Moldova",
    "Taiwan",
    "Malaysia",
    "Papua New Guinea",
    "Solomon Islands",
    "Bhutan",
    "Vietnam",
    "Cambodia",
    "Azerbaijan",
    "Armenia",
    "Georgia",
    "San Marino",
    "Norfolk Island",
    "Cocos Islands",
    "Cook Islands",
    "Kiribati",
    "Niue",
    "Aruba",
    "Pitcairn Islands",
    "Christmas Island",
    "Falkland Islands",
    "Gibraltar",
    "South Georgia and the South Sandwich Islands",
    "Monaco",
    "Marshall Islands",
    "Maldives",
    "Vatican City"
]

# dissolve geometries as NAME_2 (subregion) level
LEVEL2_REGIONS = [
    "Canada",
    "France",
    "Spain",
    "United Kingdom",
    "United States",
    "Finland",
    "Germany",
    "Brazil",
    "Australia",
    "China"
]

